hourly_job:
  cron: '0 * * * *'  # Run every hour at the 0th minute
  class: 'HourlyJob'
  queue: 'default'
  description: 'Run Hourly Job'


daily_job:
  cron: '59 23 * * *'  # Run every day At 23:59
  class: 'DailyJob'
  queue: 'default'
  description: 'Run Hourly Job'
